# =============================================================================
# SPRINT CASES -- the six Berlin-2009 finals, partitioned by Briand et al. (2025)
#
# Eur J Appl Physiol 125:3521-3541, doi 10.1007/s00421-025-05831-0; the analysis
# is the runrgetics package. These are the sprint counterpart of the Gastin case
# figures in gastin_cases.R, and they plug into the same channel: same columns,
# same units, same above-rest convention.
#
# WHAT IS A CASE HERE. Two different things, and the difference is the point.
#
#   * the DEMAND is a MEASUREMENT -- metabolic power from di Prampero's
#     equivalent-slope method applied to the published split times, flat cost
#     3.8 J/kg/m. This is what the simulator is driven with.
#   * the three SUPPLIES are a MODEL -- Briand et al.'s partition of that same
#     demand into a log-normal alactic term, a bi-exponential lactic term and a
#     mono-exponential aerobic term. This is what the simulator is compared with.
#
# So, unlike the Gastin cases, the three supplies DO NOT sum to the demand: they
# sum to the fitted total, which differs from the measurement by the fit residual
# -- 1.6 to 6.0 W/kg RMSE, and -1.05% to 0.05% of total energy. That gap is
# visible on the figure as daylight between the top dashed line and the demand
# line, and it is the inductive model's own error bar. Do not close it by
# construction -- the whole exercise is to see whether the hydraulic model can
# land on the same partition of a demand neither model chose.
#
# UNITS. Stored natively in W/kg above rest, which is what runrgetics works in.
# sprint_case() converts to mL O2 equivalent / kg / min to match gastin_case(),
# because that is the unit the app's case channel speaks.
#
# GENERATED by data-raw/generate_sprint_cases.R -- do not edit by hand.
# =============================================================================

# Formalised parameterisation of Briand et al. (2025): only the two peak powers
# differ between events; everything below is common to all six.
SPRINT_CONST <- list(mu = -0.4, sigma = 1, k1 = 2.75, k2 = 35, tau_aer = 23, bmr = 1.2)

SPRINT_CASES <- list(

  m100 = list(
    label    = "Men's 100 m — Bolt, 9.58 s",
    event    = "Men's 100 m", athlete = "Bolt",
    MAP      = 24.5,        # W/kg, gross
    duration = 9.430,       # running time, s (official time less reaction time)
    official = 9.58,        # official time, s
    reaction = 0.146,
    pal_max  = 138.8624,      # W/kg, fitted
    pla_max  = 47.4419,      # W/kg, fitted
    # measured metabolic power (W/kg above rest), thinned to 0.05 W/kg on 99 nodes
    demand_t = c(
      0.000, 0.010, 0.020, 0.030, 0.040, 0.050, 0.060, 0.070,
      0.080, 0.090, 0.100, 0.110, 0.120, 0.130, 0.140, 0.150,
      0.160, 0.170, 0.180, 0.190, 0.200, 0.210, 0.220, 0.230,
      0.240, 0.250, 0.260, 0.270, 0.280, 0.300, 0.320, 0.340,
      0.360, 0.380, 0.400, 0.420, 0.430, 0.450, 0.470, 0.480,
      0.500, 0.520, 0.550, 0.570, 0.600, 0.630, 0.660, 0.680,
      0.700, 0.720, 0.750, 0.790, 0.810, 0.840, 0.880, 0.920,
      0.960, 1.000, 1.010, 1.060, 1.120, 1.170, 1.230, 1.290,
      1.350, 1.410, 1.480, 1.540, 1.610, 1.680, 1.750, 1.820,
      1.890, 1.960, 2.030, 2.100, 2.170, 2.240, 2.310, 2.450,
      2.600, 2.750, 2.910, 3.080, 3.250, 3.410, 3.580, 3.750,
      3.940, 4.140, 4.350, 4.580, 4.830, 5.180, 5.580, 6.030,
      6.540, 6.550, 9.430),
    demand_p = c(
      0.000, 6.616, 13.015, 19.203, 25.187, 30.972, 36.562, 41.965,
      47.183, 52.224, 57.091, 61.790, 66.324, 70.699, 74.919, 78.988,
      82.911, 86.691, 90.332, 93.838, 97.214, 100.462, 103.586, 106.589,
      109.476, 112.248, 114.910, 117.464, 119.914, 124.512, 128.725, 132.575,
      136.083, 139.267, 142.146, 144.736, 145.928, 148.116, 150.055, 150.935,
      152.525, 153.900, 155.586, 156.474, 157.482, 158.130, 158.449, 158.493,
      158.411, 158.212, 157.707, 156.684, 156.037, 154.912, 153.151, 151.126,
      148.872, 146.418, 147.213, 144.157, 140.668, 137.893, 134.702, 131.645,
      128.709, 125.884, 122.718, 120.109, 117.182, 114.379, 111.695, 109.130,
      106.680, 104.345, 102.122, 100.009, 98.004, 96.104, 94.305, 90.999,
      87.859, 85.099, 82.529, 80.173, 78.152, 76.516, 75.020, 73.738,
      72.521, 71.447, 70.507, 69.659, 68.912, 68.103, 67.429, 66.897,
      66.490, 65.079, 61.671)
  ),

  m200 = list(
    label    = "Men's 200 m — Bolt, 19.19 s",
    event    = "Men's 200 m", athlete = "Bolt",
    MAP      = 24.5,        # W/kg, gross
    duration = 19.050,       # running time, s (official time less reaction time)
    official = 19.19,        # official time, s
    reaction = 0.133,
    pal_max  = 88.4189,      # W/kg, fitted
    pla_max  = 48.9878,      # W/kg, fitted
    # measured metabolic power (W/kg above rest), thinned to 0.05 W/kg on 67 nodes
    demand_t = c(
      0.000, 0.020, 0.040, 0.060, 0.080, 0.100, 0.120, 0.140,
      0.150, 0.170, 0.190, 0.200, 0.220, 0.240, 0.270, 0.290,
      0.320, 0.340, 0.370, 0.390, 0.420, 0.450, 0.480, 0.500,
      0.530, 0.560, 0.590, 0.610, 0.640, 0.660, 0.690, 0.710,
      0.740, 0.790, 0.800, 0.870, 0.910, 0.960, 1.010, 1.060,
      1.170, 1.300, 1.410, 1.530, 2.120, 2.280, 2.430, 2.610,
      2.780, 2.950, 3.130, 3.320, 3.510, 3.720, 3.930, 4.150,
      4.380, 4.630, 4.890, 5.140, 5.410, 6.000, 6.690, 7.520,
      7.530, 13.250, 19.050),
    demand_p = c(
      0.000, 6.366, 12.413, 18.156, 23.605, 28.775, 33.675, 38.318,
      40.546, 44.822, 48.866, 50.803, 54.517, 58.022, 62.907, 65.927,
      70.122, 72.707, 76.281, 78.473, 81.490, 84.200, 86.621, 88.084,
      90.065, 91.803, 93.313, 94.200, 95.362, 96.030, 96.880, 97.350,
      97.921, 98.535, 99.584, 99.954, 100.027, 99.999, 99.854, 99.608,
      98.769, 97.375, 95.951, 94.226, 84.984, 82.610, 80.513, 78.180,
      76.170, 74.347, 72.615, 70.991, 69.562, 68.186, 66.998, 65.929,
      64.977, 64.105, 63.349, 62.742, 62.196, 61.306, 60.632, 60.143,
      58.674, 55.108, 51.641)
  ),

  m400 = list(
    label    = "Men's 400 m — Merritt, 44.06 s",
    event    = "Men's 400 m", athlete = "Merritt",
    MAP      = 24.5,        # W/kg, gross
    duration = 43.910,       # running time, s (official time less reaction time)
    official = 44.06,        # official time, s
    reaction = 0.161,
    pal_max  = 62.0677,      # W/kg, fitted
    pla_max  = 39.7423,      # W/kg, fitted
    # measured metabolic power (W/kg above rest), thinned to 0.05 W/kg on 62 nodes
    demand_t = c(
      0.000, 0.020, 0.040, 0.060, 0.070, 0.090, 0.110, 0.140,
      0.160, 0.190, 0.210, 0.240, 0.270, 0.300, 0.320, 0.350,
      0.380, 0.410, 0.440, 0.470, 0.490, 0.520, 0.540, 0.570,
      0.580, 0.620, 0.660, 0.700, 0.740, 0.780, 0.830, 0.880,
      0.930, 0.980, 1.040, 1.120, 1.210, 1.310, 1.410, 1.520,
      1.650, 2.290, 2.450, 2.610, 2.820, 3.030, 3.240, 3.460,
      3.710, 3.970, 4.250, 4.540, 4.860, 5.200, 5.580, 5.990,
      6.490, 7.050, 8.450, 8.460, 25.920, 43.910),
    demand_p = c(
      0.000, 4.575, 8.920, 13.042, 15.024, 18.831, 22.438, 27.493,
      30.637, 35.031, 37.756, 41.556, 45.027, 48.189, 50.136, 52.826,
      55.256, 57.441, 59.397, 61.137, 62.184, 63.594, 64.432, 65.546,
      66.537, 67.788, 68.860, 69.774, 70.545, 71.188, 71.832, 72.319,
      72.667, 72.893, 73.023, 72.992, 72.728, 72.210, 71.511, 70.590,
      69.364, 62.838, 61.341, 59.947, 58.285, 56.812, 55.520, 54.344,
      53.204, 52.211, 51.325, 50.576, 49.909, 49.347, 48.858, 48.457,
      48.098, 47.817, 47.439, 46.907, 41.747, 36.790)
  ),

  w100 = list(
    label    = "Women's 100 m — Fraser-Pryce, 10.73 s",
    event    = "Women's 100 m", athlete = "Fraser-Pryce",
    MAP      = 21.0,        # W/kg, gross
    duration = 10.580,       # running time, s (official time less reaction time)
    official = 10.73,        # official time, s
    reaction = 0.146,
    pal_max  = 89.0700,      # W/kg, fitted
    pla_max  = 41.0181,      # W/kg, fitted
    # measured metabolic power (W/kg above rest), thinned to 0.05 W/kg on 71 nodes
    demand_t = c(
      0.000, 0.010, 0.020, 0.030, 0.040, 0.050, 0.060, 0.070,
      0.090, 0.110, 0.130, 0.150, 0.170, 0.190, 0.210, 0.230,
      0.250, 0.270, 0.290, 0.300, 0.320, 0.340, 0.370, 0.390,
      0.420, 0.440, 0.470, 0.490, 0.520, 0.540, 0.570, 0.600,
      0.630, 0.660, 0.700, 0.730, 0.770, 0.780, 0.840, 0.900,
      0.970, 1.050, 1.130, 1.220, 1.660, 1.780, 1.890, 2.020,
      2.140, 2.260, 2.390, 2.530, 2.680, 2.830, 2.990, 3.150,
      3.320, 3.500, 3.680, 3.860, 4.040, 4.230, 4.430, 4.870,
      5.370, 5.830, 6.350, 6.950, 7.670, 7.680, 10.580),
    demand_p = c(
      0.000, 3.884, 7.651, 11.304, 14.847, 18.282, 21.612, 24.839,
      30.995, 36.771, 42.184, 47.253, 51.995, 56.425, 60.560, 64.413,
      67.999, 71.330, 74.421, 75.879, 78.629, 81.167, 84.597, 86.648,
      89.394, 91.017, 93.160, 94.407, 96.021, 96.937, 98.087, 98.985,
      99.652, 100.105, 100.404, 100.419, 100.186, 101.075, 100.397, 99.565,
      98.442, 97.001, 95.436, 93.568, 83.938, 81.409, 79.188, 76.705,
      74.561, 72.565, 70.572, 68.617, 66.733, 65.052, 63.465, 62.069,
      60.774, 59.587, 58.565, 57.685, 56.928, 56.242, 55.628, 54.582,
      53.768, 53.257, 52.862, 52.565, 52.349, 51.796, 49.404)
  ),

  w200 = list(
    label    = "Women's 200 m — Felix, 21.88 s",
    event    = "Women's 200 m", athlete = "Felix",
    MAP      = 21.0,        # W/kg, gross
    duration = 21.840,       # running time, s (official time less reaction time)
    official = 21.88,        # official time, s
    reaction = 0.173,
    pal_max  = 65.6061,      # W/kg, fitted
    pla_max  = 40.9288,      # W/kg, fitted
    # measured metabolic power (W/kg above rest), thinned to 0.05 W/kg on 61 nodes
    demand_t = c(
      0.000, 0.020, 0.040, 0.060, 0.070, 0.090, 0.110, 0.140,
      0.160, 0.190, 0.210, 0.240, 0.270, 0.300, 0.320, 0.350,
      0.380, 0.410, 0.430, 0.460, 0.480, 0.510, 0.550, 0.590,
      0.600, 0.630, 0.660, 0.700, 0.740, 0.780, 0.830, 0.880,
      0.930, 0.980, 1.040, 1.130, 1.230, 1.340, 1.460, 1.560,
      1.680, 2.250, 2.570, 2.750, 2.930, 3.110, 3.290, 3.480,
      3.680, 3.890, 4.110, 4.340, 4.590, 5.120, 5.760, 6.510,
      7.410, 8.530, 8.540, 15.120, 21.840),
    demand_p = c(
      0.000, 4.620, 9.012, 13.186, 15.194, 19.056, 22.722, 27.867,
      31.074, 35.565, 38.356, 42.257, 45.830, 49.096, 51.112, 53.907,
      56.440, 58.729, 60.125, 62.037, 63.195, 64.767, 66.574, 68.074,
      69.085, 70.028, 70.871, 71.854, 72.691, 73.396, 74.113, 74.667,
      75.078, 75.363, 75.557, 75.595, 75.345, 74.795, 73.951, 73.108,
      71.983, 66.151, 63.145, 61.631, 60.253, 59.011, 57.898, 56.854,
      55.887, 55.003, 54.203, 53.486, 52.827, 51.754, 50.885, 50.247,
      49.801, 49.511, 48.906, 44.761, 40.753)
  ),

  w400 = list(
    label    = "Women's 400 m — Williams, 49.32 s",
    event    = "Women's 400 m", athlete = "Williams",
    MAP      = 21.0,        # W/kg, gross
    duration = 49.120,       # running time, s (official time less reaction time)
    official = 49.32,        # official time, s
    reaction = 0.194,
    pal_max  = 52.2120,      # W/kg, fitted
    pla_max  = 36.5180,      # W/kg, fitted
    # measured metabolic power (W/kg above rest), thinned to 0.05 W/kg on 56 nodes
    demand_t = c(
      0.000, 0.020, 0.050, 0.070, 0.100, 0.120, 0.150, 0.180,
      0.210, 0.240, 0.270, 0.300, 0.330, 0.360, 0.390, 0.420,
      0.460, 0.470, 0.500, 0.530, 0.560, 0.600, 0.630, 0.670,
      0.740, 0.780, 0.820, 0.900, 0.990, 1.090, 1.170, 1.250,
      1.340, 1.440, 1.550, 1.680, 2.310, 2.630, 2.830, 3.040,
      3.260, 3.480, 3.730, 3.990, 4.270, 4.570, 4.890, 5.240,
      6.040, 6.630, 7.320, 9.130, 9.140, 22.950, 35.860, 49.120),
    demand_p = c(
      0.000, 3.913, 9.411, 12.840, 17.648, 20.640, 24.826, 28.670,
      32.192, 35.412, 38.348, 41.018, 43.437, 45.621, 47.585, 49.342,
      51.384, 52.359, 53.671, 54.857, 55.930, 57.198, 58.038, 59.026,
      60.429, 61.067, 61.602, 62.396, 62.921, 63.137, 63.089, 62.883,
      62.501, 61.933, 61.179, 60.173, 54.922, 52.566, 51.275, 50.072,
      48.971, 48.017, 47.094, 46.290, 45.573, 44.948, 44.412, 43.949,
      43.233, 42.909, 42.662, 42.368, 42.100, 38.097, 34.552, 31.095)
  )
)

# -----------------------------------------------------------------------------
# Accessors. Mirrors gastin_cases.R so the two families are interchangeable
# wherever the app handles a "case".
# -----------------------------------------------------------------------------

# Energy equivalent of O2 (J per mL), as elsewhere in the app. Repeated here
# rather than taken from designer.R so this file can be sourced on its own.
SPRINT_EQ_O2 <- 20.9

#' The three published supply curves of a case, in W/kg above rest
#'
#' Closed form, exactly as in Briand et al. (2025): a log-normal alactic term, a
#' bi-exponential lactic term normalised to peak at `pla_max`, and a
#' mono-exponential aerobic term rising to MAP less basal metabolic rate.
sprint_case_supplies <- function(cs, t) {
  k <- SPRINT_CONST
  # Reciprocal of the peak of (1 - e^(-t/k1)) e^(-t/k2), so that pla_max is the
  # ACTUAL peak lactic power rather than a scale factor. This is runrgetics'
  # bi_exponential_knorm() written out -- kept in its algebraic form so the two
  # cannot drift; it is 1/f(t_peak) with t_peak = k1 log(1 + k2/k1).
  knorm <- (k$k1 + k$k2) / (k$k2 * (k$k1 / (k$k1 + k$k2))^(k$k1 / k$k2))

  al <- cs$pal_max * exp(-(log(t) - k$mu)^2 / (2 * k$sigma^2))
  al[!is.finite(al)] <- 0                       # log(0) at the first sample
  list(
    atp_pcr = al,
    glyco   = cs$pla_max * knorm * (1 - exp(-t / k$k1)) * exp(-t / k$k2),
    aerobic = (cs$MAP - k$bmr) * (1 - exp(-t / k$tau_aer))
  )
}

#' Evaluate one sprint case on a time grid
#'
#' @param case Name in [SPRINT_CASES].
#' @param dt Grid step (s). 0.05 by default, not the 0.25 the Gastin cases use:
#'   the alactic term peaks at exp(mu) = 0.67 s and a quarter-second grid walks
#'   straight past it.
#' @return data.frame(time, demand, atp_pcr, glyco, aerobic) in mL O2
#'   equivalent / kg / min, above rest. `demand` is the MEASURED metabolic power;
#'   the three supplies are the fitted partition of it, so they sum to slightly
#'   less than `demand` -- see the header. Nothing is subtracted for resting
#'   metabolism because nothing here includes it: di Prampero's cost of running
#'   is a net cost and the aerobic term already asymptotes to MAP - BMR.
sprint_case <- function(case, dt = 0.05) {
  cs <- SPRINT_CASES[[case]]
  if (is.null(cs)) stop("Unknown sprint case: ", case)
  t <- seq(0, cs$duration, by = dt)
  if (t[length(t)] < cs$duration) t <- c(t, cs$duration)

  s <- sprint_case_supplies(cs, t)
  cvt <- 60 / SPRINT_EQ_O2                       # W/kg -> mL O2/kg/min
  d <- data.frame(
    time    = t,
    demand  = stats::approx(cs$demand_t, cs$demand_p, t, rule = 2)$y * cvt,
    atp_pcr = s$atp_pcr * cvt,
    glyco   = s$glyco   * cvt,
    aerobic = s$aerobic * cvt
  )
  attr(d, "case") <- cs
  d
}

#' A case's aerobic ceiling on the model's ABOVE-REST scale (mL O2/kg/min)
#'
#' MAP is published gross, and the simulator's ceiling is an above-rest flux, so
#' basal metabolic rate comes off it -- the same correction gastin_case_vo2max()
#' makes, arriving from the other direction.
sprint_case_vo2max <- function(case) {
  cs <- SPRINT_CASES[[case]]
  if (is.null(cs)) stop("Unknown sprint case: ", case)
  (cs$MAP - SPRINT_CONST$bmr) * 60 / SPRINT_EQ_O2
}

#' Published energy partition of a case (J/kg and %), and the measured total
#'
#' The shares are of the FITTED total, which is what Briand et al. report; the
#' measured total is carried alongside so the fit residual stays visible.
sprint_case_energies <- function(case, dt = 0.01) {
  d <- sprint_case(case, dt)
  cvt <- SPRINT_EQ_O2 / 60
  trap <- function(y) sum(0.5 * (y[-1] + y[-length(y)]) * diff(d$time)) * cvt
  E <- c(alactic = trap(d$atp_pcr), lactic = trap(d$glyco), aerobic = trap(d$aerobic))
  list(alactic = E[["alactic"]], lactic = E[["lactic"]], aerobic = E[["aerobic"]],
       total = sum(E), demand = trap(d$demand),
       share = 100 * E / sum(E))
}

SPRINT_CASE_NAMES <- c(
  "Men's 100 m — Bolt"           = "m100",
  "Men's 200 m — Bolt"           = "m200",
  "Men's 400 m — Merritt"        = "m400",
  "Women's 100 m — Fraser-Pryce" = "w100",
  "Women's 200 m — Felix"        = "w200",
  "Women's 400 m — Williams"     = "w400"
)
