# Generated by inst/hydraulic_app2/make_tour_shots.R -- do not edit by hand.
# Cursor positions inside www/tour/*.png, as per-cent of each picture.
HY2_TOUR_MARKS <- list(
  panel = list(
    ptype = c(50.00, 15.01),
    intensity = c(50.00, 19.66),
    duration = c(50.00, 26.19),
    info = c(22.49, 1.78),
    run = c(50.00, 94.52)),
  config = list(
    nudge = c(8.84, 54.03),
    refs = c(50.00, 83.00),
    apply = c(7.74, 97.15)),
  transport = list(
    play = c(4.40, 49.99),
    speed = c(23.41, 50.00),
    scrub = c(64.77, 52.38))
)
